project files/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::GET('admin/home','AdminController@index')->name('homepage'); 
Route::GET('admin' ,'Admin\LoginController@showLoginForm')->name('admin.login');
Route::POST('admin','Admin\LoginController@login');
Route::POST('admin-password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::GET('admin-password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::POST('admin-password/reset','Admin\ResetPasswordController@reset');
Route::GET('admin-password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');


Route::resource('employees','employeescontorller');
Route::resource('branches','branchController');
Route::resource('departments','departmentController');

//Ajax Calls
Route::GET('getorganiationbranches','branchController@getorganiationbranches')->name('getorganiationbranches'); 
Route::GET('testing','branchController@testing')->name('testing'); 

project files/app/department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class department extends Model
{
    //
}

project files/app/Http/Controllers/departmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
use App\department;

class departmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    public function index()
    {
        //
         $department = Auth::user()->department;
         $query =  DB::table('departments')
                    ->select('departments.*','employees.name')
                    ->join('employees', 'departments.organisation_id', '=', 'employees.id');

         switch ($department) {
              case 'Super Admin':
                                    $departments = $query->get();
                                    $permissionset =explode(",", Auth::user()->permissions);
                                    break;
             case 'Admin':
                            $organisationid = Auth::user()->id;
                            $permissionset =explode(",", Auth::user()->permissions);
                            $departments = $query->where('departments.organisation_id',$organisationid)->get();
                            
                  break;
              case 'Sub Admin': 
                            $organisationid = Auth::user()->organisationid;
                            $permissionset =explode(",", Auth::user()->permissions);
                            $branch =explode(",", Auth::user()->branch);
                            $departments = $query->where('departments.organisation_id',$organisationid)
                                                    ->where('departments.branch',$branch)
                                                 ->get();
                        break;
              default:
                            $organisationid = Auth::user()->organisationid;
                            $permissionset =explode(",", Auth::user()->permissions);
                            $branch =explode(",", Auth::user()->branch);
                            $departments = $query->where('departments.organisation_id',$organisationid)
                                                    ->where('departments.branch',$branch)
                                                 ->get();
                  break;
          }
          return view('admin/Departments/index',compact('permissionset','department','departments'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $permissionset =explode(",", Auth::user()->permissions);
        $department = Auth::user()->department;
        $branch = null;
        $branches = null;
           switch ($department) {

              case 'Super Admin':
                                    $permissionset =explode(",", Auth::user()->permissions);
                                    $branches = "";
                                    break;
             case 'Admin':
                            $organisationid = Auth::user()->id;
                             $query =  DB::table('branches')
                                        ->select('branches.*','employees.name')
                                        ->join('employees', 'branches.organisation_id', '=', 'employees.id');
                              $branches =  $query->where('branches.organisation_id',$organisationid)->get();
                       
                            $permissionset =explode(",", Auth::user()->permissions);
                            
                  break;
               case 'Sub Admin': 
                            $organisationid = Auth::user()->organisationid;
                            $permissionset =explode(",", Auth::user()->permissions);
                            $branch = Auth::user()->branch;
                            break;
              default:
                  # code...
                  break;
          }
          if(in_array("6", $permissionset)){
             return view('admin/Departments/create',compact('permissionset','branches','branch'));
         }else{
            return "dnt have permission";
         }
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $department = new department;
        $department->deptname = $request->deptname;
        $department->permissions = $request->Permissions;
        $department->organisation_id = $request->Organisationid;
        $department->branch = $request->branch;
        $department->code = $request->deptcode;
        $department->save();
        return redirect('/departments'); 

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $permissionset =explode(",", Auth::user()->permissions);
        $department = department::find($id);
        $query =  DB::table('branches')
                    ->select('branches.*','employees.name')
                    ->join('employees', 'branches.organisation_id', '=', 'employees.id');
        $branches =  $query->where('branches.organisation_id',$department->organisation_id)->get();
        return view('admin/Departments/edit',compact('permissionset','department','branches'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $department = department::find($id);
     
        $department->deptname = $request->deptname;
        $department->permissions = $request->Permissions;
        $department->organisation_id = $request->Organisationid;
        $department->branch = $request->branch;
        $department->code = $request->deptcode;
        $department->save();
        return redirect('/departments'); 

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

project files/resources/views/admin/Departments/branches.blade.php
<!-- @foreach($branches as $branch)

	{{$branch->branchname}}
@endforeach -->
                                                <label for="inputState" class="col-form-label">Branch *</label>
                                                <select id="branch" class="form-control" name="branch">
                                                	 @foreach($branches as $branch)
														<option value="{{$branch->branchname}}">{{$branch->branchname}}</option>
                                            		@endforeach</select>
                                            </div

project files/resources/views/admin/Departments/index.blade.php
@include('admin.header',['mainTitle' => "Departments"])
<!-- DataTables -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ URL::asset('dashboard/plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <!-- Responsive datatable examples -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />

        <!-- Multi Item Selection examples -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/select.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<style type="text/css">
	.addnew{
		text-align: right;
		margin-bottom: 20px;
	}
</style>

        		  <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">

                                <div class="card-box table-responsive">
                                 @if(in_array("5", $permissionset))
                                	<div class="addnew">
                                		 <div class="button-list">
                                		 	
                                		 		<a href="/departments/create"  class="btn btn-primary waves-light waves-effect">Add </a>
                                		 </div>
                                	</div>
                                @endif
                                    <table id="responsive-datatable" class="table table-bordered table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Permissions</th>
                                            <th>Branch</th>
                                            <th>Organisation</th>
                                              <th>Actions</th>
                                        </tr>
                                        </thead>


                                        <tbody>
                                        	@foreach($departments as $department)
                                        		 	<tr>
			                                            <td>{{$department->deptname}}</td>
			                                            <td>{{$department->permissions}}</td>
			                                            <td>{{$department->branch}}</td>
			                                            <td>{{$department->name}}</td>
                                                        <td><a href="{{route('departments.edit',$department->id)}}"><i class="fa fa-edit"></i> </a> <i class="fa fa-trash-o"></i></td>
			                                        </tr>
                                        	@endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div> <!-- end row -->

                 </div>
              </div>

@include('admin.footer') 

        <!-- Required datatable js -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <!-- Buttons examples -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/jszip.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/vfs_fonts.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.print.min.js') }}"></script>

        <!-- Key Tables -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.keyTable.min.js') }}"></script>

        <!-- Responsive examples -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

        <!-- Selection table -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.select.min.js') }}"></script>

        <!-- App js -->
        <script src="{{ URL::asset('dashboard/assets/js/jquery.core.js') }}"></script>
        <script src="{{ URL::asset('dashboard/assets/js/jquery.app.js') }}"></script>

        <script type="text/javascript">
            $(document).ready(function() {

              

                // Responsive Datatable
                $('#responsive-datatable').DataTable();

              
            } );

        </script>