project files/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::GET('admin/home','AdminController@index')->name('homepage'); 
Route::GET('admin' ,'Admin\LoginController@showLoginForm')->name('admin.login');
Route::POST('admin','Admin\LoginController@login');
Route::POST('admin-password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::GET('admin-password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::POST('admin-password/reset','Admin\ResetPasswordController@reset');
Route::GET('admin-password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');


Route::resource('employees','employeescontorller');
Route::resource('branches','branchController');
Route::resource('departments','departmentController');

//Ajax Calls
Route::GET('getorganiationbranches','branchController@getorganiationbranches')->name('getorganiationbranches'); 
Route::GET('testing','branchController@testing')->name('testing'); 

project files/app/branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class branch extends Model
{
    //
}

project files/app/Http/Controllers/branchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\branch;
use Illuminate\Support\Facades\Auth;
use DB;
class branchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    public function index()
    {
        //
         $department = Auth::user()->department;
         $query =  DB::table('branches')
                    ->select('branches.*','employees.name')
                    ->join('employees', 'branches.organisation_id', '=', 'employees.id');
          switch ($department) {

              case 'Super Admin':
                                    $branches = $query->get();
                                    $permissionset =explode(",", Auth::user()->permissions);
                                    break;
             case 'Admin':
                            $organisationid = Auth::user()->id;
                            $permissionset =explode(",", Auth::user()->permissions);
                            $branches =  $query->where('branches.organisation_id',$organisationid)
                                                ->get();
                  break;
              case 'Sub Admin':
                            $permissionset =explode(",", Auth::user()->permissions);
                            $organisationid = Auth::user()->organisationid;
                            $branches =  $query->where('branches.organisation_id',$organisationid)
                                                ->get();
                        break;
              default:
                  $permissionset =explode(",", Auth::user()->permissions);
                            $organisationid = Auth::user()->organisationid;
                            $branches =  $query->where('branches.organisation_id',$organisationid)
                                                ->get();
                  break;
          }

        
         
         if(in_array("9", $permissionset)){
                return view('admin/Branches/index',compact('branches','permissionset'));
         }else{
            return "dnt have permission";
         }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $department = Auth::user()->department;
          switch ($department) {

              case 'Super Admin':
                                    $permissionset =explode(",", Auth::user()->permissions);
                                    break;
             case 'Admin':
                            $organisationid = Auth::user()->id;
                            $permissionset =explode(",", Auth::user()->permissions);
                            
                  break;
              case 'Sub Admin': 
                             $permissionset =explode(",", Auth::user()->permissions);
                            $organisationid = Auth::user()->organisationid;
                            break;
              default:
                   $permissionset =explode(",", Auth::user()->permissions);
                            $organisationid = Auth::user()->organisationid;
                  break;
          }
          if(in_array("10", $permissionset)){
                return view('admin/Branches/create',compact('permissionset'));
         }else{
            return "dnt have permission";
         }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $department = Auth::user()->department;
        $branch = new branch;
        $branch->branchname  = $request->branchname;
        $branch->branch_code  = $request->branchcode;
        $branch->address  = $request->branchaddress;
        $branch->phone_no  = $request->branchphoneno;
        $branch->email_id  = $request->branchemail;
        $branch->no_shifts  = $request->shifts;
        $branch->default_shifts  = $request->defaultshifts;
        $branch->organisation_id  = $request->Organisationid;
        $branch->created_by  = $department;
        if($request->flexiblework  == "on"){
            $flexiblework = 1;
        }else{
            $flexiblework = 0;
        }
        $branch->flexible_work  = $flexiblework;
        if($request->extrapay  == "on"){
            $extra_payvalue = 1;
        }else{
            $extra_payvalue = 0;
        }
        $branch->extra_pay  = $extra_payvalue;
        $branch->save();
        return redirect("/branches");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $permissionset =explode(",", Auth::user()->permissions);
        $branch = branch::find($id);
        if(in_array("11", $permissionset)){
                return view('admin/Branches/edit',compact('permissionset','branch'));
         }else{
            return "dnt have permission";
         }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $branch = branch::find($id);
         $branch->branchname  = $request->branchname;
        $branch->branch_code  = $request->branchcode;
        $branch->address  = $request->branchaddress;
        $branch->phone_no  = $request->branchphoneno;
        $branch->email_id  = $request->branchemail;
        $branch->no_shifts  = $request->shifts;
        $branch->default_shifts  = $request->defaultshifts;
        $branch->organisation_id  = $request->Organisationid;
        if($request->flexiblework  == "on"){
            $flexiblework = 1;
        }else{
            $flexiblework = 0;
        }
        $branch->flexible_work  = $flexiblework;
        if($request->extrapay  == "on"){
            $extra_payvalue = 1;
        }else{
            $extra_payvalue = 0;
        }
        $branch->extra_pay  = $extra_payvalue;
        $branch->save();
        return redirect("/branches");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }



    public function getorganiationbranches(Request $request){
       $organisationid = $request->id;
       $query =  DB::table('branches')
                    ->select('branches.*','employees.name')
                    ->join('employees', 'branches.organisation_id', '=', 'employees.id');
          $branches =  $query->where('branches.organisation_id',$organisationid)->get();
      return view('admin/Departments/branches',compact('branches'));
    }
      public function testing(Request $request){
       $organisationid = $request->xml;
       return $organisationid;
    }
}

project files/resources/views/admin/Branches/index.blade.php
@include('admin.header',['mainTitle' => "Branches"])
<!-- DataTables -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ URL::asset('dashboard/plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <!-- Responsive datatable examples -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />

        <!-- Multi Item Selection examples -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/select.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<style type="text/css">
	.addnew{
		text-align: right;
		margin-bottom: 20px;
	}
</style>

        		  <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">

                                <div class="card-box table-responsive">
                                 @if(in_array("10", $permissionset))
                                	<div class="addnew">
                                		 <div class="button-list">
                                		 	
                                		 		<a href="/branches/create"  class="btn btn-primary waves-light waves-effect">Add </a>
                                		 </div>
                                	</div>
                                @endif
                                    <table id="responsive-datatable" class="table table-bordered table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Code</th>
                                            <th>Email Id</th>
                                            <th>Phone Num</th>
                                            <th>Organisation</th>
                                            <th>Created By</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>


                                        <tbody>
                                        	@foreach($branches as $branch)
                                        		 	<tr>
			                                            <td>{{$branch->branchname}}</td>
                                                        <td>{{$branch->branch_code}}</td>
			                                            <td>{{$branch->email_id}}</td>
			                                            <td>{{$branch->phone_no}}</td>
                                                        <td>{{$branch->name}}</td>
                                                        <td>{{$branch->created_by}}</td>
			                                            <td><a href="{{route('branches.edit',$branch->id)}}"><i class="fa fa-edit"></i> </a> <i class="fa fa-trash-o"></i></td>
			                                        </tr>
                                        	@endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div> <!-- end row -->

                 </div>
              </div>

@include('admin.footer') 

        <!-- Required datatable js -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <!-- Buttons examples -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/jszip.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/vfs_fonts.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.print.min.js') }}"></script>

        <!-- Key Tables -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.keyTable.min.js') }}"></script>

        <!-- Responsive examples -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

        <!-- Selection table -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.select.min.js') }}"></script>

        <!-- App js -->
        <script src="{{ URL::asset('dashboard/assets/js/jquery.core.js') }}"></script>
        <script src="{{ URL::asset('dashboard/assets/js/jquery.app.js') }}"></script>

        <script type="text/javascript">
            $(document).ready(function() {

              

                // Responsive Datatable
                $('#responsive-datatable').DataTable();

              
            } );

        </script>