project files/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::GET('admin/home','AdminController@index')->name('homepage'); 
Route::GET('admin' ,'Admin\LoginController@showLoginForm')->name('admin.login');
Route::POST('admin','Admin\LoginController@login');
Route::POST('admin-password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::GET('admin-password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::POST('admin-password/reset','Admin\ResetPasswordController@reset');
Route::GET('admin-password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');


Route::resource('employees','employeescontorller');
Route::resource('branches','branchController');
Route::resource('departments','departmentController');

//Ajax Calls
Route::GET('getorganiationbranches','branchController@getorganiationbranches')->name('getorganiationbranches'); 
Route::GET('testing','branchController@testing')->name('testing'); 

project files/app/Employee.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Employee extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

project files/resources/views/admin/Employee/index.blade.php
@include('admin.header',['mainTitle' => "Employees"])
<!-- DataTables -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ URL::asset('dashboard/plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <!-- Responsive datatable examples -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />

        <!-- Multi Item Selection examples -->
        <link href="{{ URL::asset('dashboard/plugins/datatables/select.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<style type="text/css">
	.addnew{
		text-align: right;
		margin-bottom: 20px;
	}
</style>

        		  <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">

                                <div class="card-box table-responsive">
                                 @if(in_array("1", $permissionset))
                                	<div class="addnew">
                                		 <div class="button-list">
                                		 	
                                		 		<a href="/employees/create"  class="btn btn-primary waves-light waves-effect">Add </a>
                                		 </div>
                                	</div>
                                @endif
                                    <table id="responsive-datatable" class="table table-bordered table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Department</th>
                                            <th>Branch</th>
                                            <th>Email Id</th>
                                            <th>Phone Num</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>


                                        <tbody>
                                        	@foreach($employess as $employee)
                                        		 	<tr>
			                                            <td>{{$employee->name}}</td>
			                                            <td>{{$employee->department}}</td>
			                                            <td>{{$employee->branch}}</td>
			                                            <td>{{$employee->email}}</td>
                                                        <td>{{$employee->phoneno}}</td>
			                                            <td><a href="{{route('employees.edit',$employee->id)}}"><i class="fa fa-edit"></i> </a> <i class="fa fa-trash-o"></i></td>
			                                        </tr>
                                        	@endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div> <!-- end row -->

                 </div>
              </div>

@include('admin.footer') 

        <!-- Required datatable js -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
        <!-- Buttons examples -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.buttons.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/jszip.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/pdfmake.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/vfs_fonts.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.html5.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/buttons.print.min.js') }}"></script>

        <!-- Key Tables -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.keyTable.min.js') }}"></script>

        <!-- Responsive examples -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.responsive.min.js') }}"></script>
        <script src="{{ URL::asset('dashboard/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

        <!-- Selection table -->
        <script src="{{ URL::asset('dashboard/plugins/datatables/dataTables.select.min.js') }}"></script>

        <!-- App js -->
        <script src="{{ URL::asset('dashboard/assets/js/jquery.core.js') }}"></script>
        <script src="{{ URL::asset('dashboard/assets/js/jquery.app.js') }}"></script>

        <script type="text/javascript">
            $(document).ready(function() {

              

                // Responsive Datatable
                $('#responsive-datatable').DataTable();

              
            } );

        </script>